# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ipos_cafe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ipos_cafe
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'Firebase/Auth'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end
